APP_WIDTH = 525
APP_HEIGHT = 850
WIDGET_WIDTH = 485
WIDGET_HEIGHT_HD_RATIO = (1080 * WIDGET_WIDTH) / 1920
FIELD_HEIGHT = 30
BYTES_PER_MEGABYTE = 1048576
ESCAPE_KEY_CODE = 16777216

DEFAULT_IMAGE_PATH = 'C:/Documents'
TEMP_IMAGE_PATH = 'temp/temp_ss.png'
ICON_IMAGE_PATH = './assets/icon.png'
DEFAULT_PREVIEW_PATH = './assets/default_preview.png'
THUMBNAIL_WIDTH = 500
THUMBNAIL_HEIGHT = 281

IMAGE_FORMATS = {
    '.jpg': 'JPEG',
    '.png': 'PNG',
    '.bmp': 'BMP'
}

CONFIG_FILE = 'config.json'
CONFIG_LOCK_FILE = 'config.lock'
